### PR TITLE
t2h 126 state recovery basic

### PR DESCRIPTION
**Pull request by emargetis**
### Overview
In order to ensure that each client remains up to date with the server state, the case of missing delta updates needed to be addressed. There are multiple ways to handle this problem, but the most straightforward and robust way is to make the client client responsible for staying in-sync. Because we are sending delta updates from the server to the client on a time-based interval that have a unique `snapshotID` that is incremented for every update, the client can store this this value and use it to determine if the next `snapshotID` it receives is the correct one. In other words, the ID is one more than the previous one it has stored. In the case that this is false, the client will send a special `reset` request which lets the server know to immediately send over the entire state, not just deltas. Note that because delta updates are idempotent, we don't have to worry about them already being contained in a state update and a subsequent delta update.

### Updates
- Implemented sending the snapshot ID on `init` which is one less than current snapshot ID. This will allow the client to catch the first delta if it goes missing
- Implemented sending a `reset` type which will send the whole cannon, similar to `init`. This `reset` logic could be upgraded to send missing deltas if we decided to preserve them in the future
- Implemented `updateType` property on all server sent messages to help client differentiate between message types rather than relying on present or missing properties as a way to determine what to do with the message
- Implemented client-side logic to handle all three `updateType`s: `reset`, `init`, and `delta`

### Testing
- In order to test this system, I simulated lost messages by randomly skipping over the `ws.send` method for each client from time to time using conditional logic with `Math.random()`. Results were as expected - clients sent reset requests and got back up to date quickly.

### Further Development
- A `reset` request that sends the entire state can be an expensive operation so it may make sense to use some kind stored log of patch updates (known as a write-ahead-log aka WAL) that can be filtered and sent to the client to get them up to date
- A bigger overhaul solution that could also be considered is moving a way from a time-based interval notification system of delta updates to one based on a pull request initiated by the client when the server notifies them. This way, each delta update sent to a client could be tailored to their specific needs to get them up to date. This solution increases complexity on the server and may also lead to a longer turnaround time for a `reset` from the server because it would need to filter the patches. Further investigation is required.

### CODE REVIEW

**Comment by emargetis** [comment]
Need to update a reset to remove pending transactions so if a patch comes through then they are not reapplied

**Review by jgoteam — COMMENTED** [review]
Maybe `initState` on line 137 in `index.mjs` should be called `resetState` or `resettedState` instead? Other than that looks good to me

**Review by jgoteam — APPROVED** [review]
Nice changes. The new update types are intuitive and seem to cover the range of updates needed.

**Comment by emargetis** [comment]
@jgoteam  good call on the `initState` variable. I changed it to `resetState`.

**Pull request merged**
